CREATE SCHEMA "quiz";
--> statement-breakpoint
CREATE TYPE "public"."locales" AS ENUM('en', 'fr');--> statement-breakpoint
CREATE TYPE "quiz"."answer_type" AS ENUM('single_choice', 'multiple_choice', 'boolean', 'text', 'number');--> statement-breakpoint
CREATE TABLE "quiz"."answer_choices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz"."answer_choices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"answer_type_id" integer NOT NULL,
	"choice" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quiz"."answer_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz"."answer_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" "quiz"."answer_type" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quiz"."questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz"."questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quiz_id" integer NOT NULL,
	"answer_type_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quiz"."questions_str" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz"."questions_str_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_id" integer NOT NULL,
	"content" text NOT NULL,
	"locale" "locales" DEFAULT 'en' NOT NULL,
	CONSTRAINT "questions_str_locale_unique" UNIQUE("question_id","locale")
);
--> statement-breakpoint
CREATE TABLE "quiz"."quizzes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz"."quizzes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"iso_3166_1" varchar(2)
);
--> statement-breakpoint
CREATE TABLE "quiz"."result_answers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz"."result_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" uuid NOT NULL,
	"question_id" integer NOT NULL,
	"answer_choice_id" integer,
	"value" text
);
--> statement-breakpoint
CREATE TABLE "quiz"."results" (
	"id" uuid PRIMARY KEY NOT NULL,
	"quiz_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "quiz"."answer_choices" ADD CONSTRAINT "answer_choices_answer_type_id_answer_types_id_fk" FOREIGN KEY ("answer_type_id") REFERENCES "quiz"."answer_types"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."questions" ADD CONSTRAINT "questions_quiz_id_quizzes_id_fk" FOREIGN KEY ("quiz_id") REFERENCES "quiz"."quizzes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."questions" ADD CONSTRAINT "questions_answer_type_id_answer_types_id_fk" FOREIGN KEY ("answer_type_id") REFERENCES "quiz"."answer_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."questions_str" ADD CONSTRAINT "questions_str_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "quiz"."questions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."result_answers" ADD CONSTRAINT "result_answers_result_id_results_id_fk" FOREIGN KEY ("result_id") REFERENCES "quiz"."results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."result_answers" ADD CONSTRAINT "result_answers_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "quiz"."questions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."result_answers" ADD CONSTRAINT "result_answers_answer_choice_id_answer_choices_id_fk" FOREIGN KEY ("answer_choice_id") REFERENCES "quiz"."answer_choices"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quiz"."results" ADD CONSTRAINT "results_quiz_id_quizzes_id_fk" FOREIGN KEY ("quiz_id") REFERENCES "quiz"."quizzes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "answer_choices_answer_type_id_index" ON "quiz"."answer_choices" USING btree ("answer_type_id");--> statement-breakpoint
CREATE INDEX "questions_str_question_id_index" ON "quiz"."questions_str" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "questions_str_locale_index" ON "quiz"."questions_str" USING btree ("locale");--> statement-breakpoint
CREATE INDEX "quizzes_iso_3166_1_index" ON "quiz"."quizzes" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "result_answers_result_id_index" ON "quiz"."result_answers" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "result_answers_question_id_index" ON "quiz"."result_answers" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "result_answers_answer_choice_id_index" ON "quiz"."result_answers" USING btree ("answer_choice_id");--> statement-breakpoint
CREATE INDEX "results_quiz_id_index" ON "quiz"."results" USING btree ("quiz_id");